### ISSUE TITLE
use_blend and use_halfmixing both True?

### ISSUE THREAD

**Issue by darius-lam** [Xrvitd/ComboStoc#1]
Are both use_blend and use_halfmixing supposed to be both set to True to achieve the "ComboStoc-TB" approach?

Or is it just use_halfmixing? It would seem that the combination sets half to original T and half to blended T + combostoc T.

**Comment by Xrvitd** [comment]
"ComboStoc-TB" only use_blend and need to change the time step embedding module C_C = C_H (line 33 in models.py).
________________________________
发件人: Lamma ***@***.***>
发送时间: 2024年8月21日 17:11
收件人: Xrvitd/ComboStoc ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Xrvitd/ComboStoc] use_blend and use_halfmixing both True? (Issue #1)


This is an external email.

Are both use_blend and use_halfmixing supposed to be both set to True to achieve the "ComboStoc-TB" approach?

Or is it just use_halfmixing? It would seem that the combination sets half to original T and half to blended T + combostoc T.

―
